# update_stan.yml
# for apt update/upgrade of stan from mb
---
- hosts: servers
  become: true
  tasks:
  - name: update apt repos and cache
    apt: update_cache=yes cache_valid_time=3600
  - name: upgrade all apt things
    apt: upgrade=dist
    register: apt
  - debug: msg={{ apt.stdout.split('\n')[:-1] }}